# Фильтр для обнаружения очистки логов
# Критически важно для соответствия ОАЦ

[Definition]
failregex = .*journalctl.*cleared.*
            .*rm.*\/var\/log\/.*
            .*truncate.*\/var\/log\/.*
            *>.*\/var\/log\/.*
            .*shred.*\/var\/log\/.*
ignoreregex =
